export const fakeProduct = [
  {
    name: 'Allow Account Password Reset',
    value: '12',
    order: 12,
    hostcode: null,
    key: '12',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow Account Activation',
    value: '13',
    order: 13,
    hostcode: null,
    key: '13',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow Account Modificaton',
    value: '14',
    order: 14,
    hostcode: null,
    key: '14',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow Account Creation',
    value: '15',
    order: 15,
    hostcode: null,
    key: '15',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow Account Inactivation',
    value: '16',
    order: 16,
    hostcode: null,
    key: '16',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow Account Security Questions',
    value: '17',
    order: 17,
    hostcode: null,
    key: '17',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow Direct Deposit Modification',
    value: '18',
    order: 18,
    hostcode: null,
    key: '18',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow Account OOC Unlock',
    value: '19',
    order: 19,
    hostcode: null,
    key: '19',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow Claim Impersonation',
    value: '21',
    order: 21,
    hostcode: null,
    key: '21',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow Claim Creation',
    value: '22',
    order: 22,
    hostcode: null,
    key: '22',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow User Management',
    value: '30',
    order: 30,
    hostcode: null,
    key: '30',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow User Rights Management',
    value: '31',
    order: 31,
    hostcode: null,
    key: '31',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow Table Managment',
    value: '40',
    order: 40,
    hostcode: null,
    key: '40',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow Archived Reports',
    value: '50',
    order: 50,
    hostcode: null,
    key: '50',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow Archived Reports All',
    value: '51',
    order: 51,
    hostcode: null,
    key: '51',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow Employer Search',
    value: '60',
    order: 60,
    hostcode: null,
    key: '60',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow Employer Unlock',
    value: '61',
    order: 61,
    hostcode: null,
    key: '61',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow Employer Password Reset',
    value: '62',
    order: 62,
    hostcode: null,
    key: '62',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow Employer Activation',
    value: '63',
    order: 63,
    hostcode: null,
    key: '63',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow Employer Modificaton',
    value: '64',
    order: 64,
    hostcode: null,
    key: '64',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow Employer Creation',
    value: '65',
    order: 65,
    hostcode: null,
    key: '65',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow Employer Inactivation',
    value: '66',
    order: 66,
    hostcode: null,
    key: '66',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow Employer Security Questions',
    value: '67',
    order: 67,
    hostcode: null,
    key: '67',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow Employer Add User',
    value: '68',
    order: 68,
    hostcode: null,
    key: '68',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow DD Warrant Cancellation',
    value: '70',
    order: 70,
    hostcode: null,
    key: '70',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow Service Company Search',
    value: '80',
    order: 80,
    hostcode: null,
    key: '80',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow Service Company Unlock Account',
    value: '81',
    order: 81,
    hostcode: null,
    key: '81',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow Service Company Password Reset',
    value: '82',
    order: 82,
    hostcode: null,
    key: '82',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow Service Company Online Profile Maintenance Edit',
    value: '84',
    order: 84,
    hostcode: null,
    key: '84',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow Service Company Inactivation and Reactivation',
    value: '86',
    order: 86,
    hostcode: null,
    key: '86',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow Service Company Security Questions',
    value: '87',
    order: 87,
    hostcode: null,
    key: '87',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow Service Company Add User',
    value: '88',
    order: 88,
    hostcode: null,
    key: '88',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow Service Company View of Employers',
    value: '89',
    order: 89,
    hostcode: null,
    key: '89',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow Appeal Search',
    value: '100',
    order: 100,
    hostcode: null,
    key: '100',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow Appeal Creation',
    value: '101',
    order: 101,
    hostcode: null,
    key: '101',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow Appeal Schedule Management',
    value: '102',
    order: 102,
    hostcode: null,
    key: '102',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow Appeal Finalize',
    value: '103',
    order: 103,
    hostcode: null,
    key: '103',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow Appeal Amend',
    value: '104',
    order: 104,
    hostcode: null,
    key: '104',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow Appeal Cancel',
    value: '105',
    order: 105,
    hostcode: null,
    key: '105',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow Appeal Edit',
    value: '106',
    order: 106,
    hostcode: null,
    key: '106',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow Appeal Edit Employer',
    value: '107',
    order: 107,
    hostcode: null,
    key: '107',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow Appeal AHO Management',
    value: '110',
    order: 110,
    hostcode: null,
    key: '110',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow Appeal AHO Preference Management',
    value: '111',
    order: 111,
    hostcode: null,
    key: '111',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow Appeal AHO Calendar View',
    value: '112',
    order: 112,
    hostcode: null,
    key: '112',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow Appeal AHO Rights Management',
    value: '113',
    order: 113,
    hostcode: null,
    key: '113',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow Appeal AHO Pref Calendar View',
    value: '114',
    order: 114,
    hostcode: null,
    key: '114',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow Appeal Appearance View',
    value: '120',
    order: 120,
    hostcode: null,
    key: '120',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow Appeal Appearance Edit',
    value: '121',
    order: 121,
    hostcode: null,
    key: '121',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow Appeal Log Notes View',
    value: '130',
    order: 130,
    hostcode: null,
    key: '130',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow Appeal Log Notes Edit',
    value: '131',
    order: 131,
    hostcode: null,
    key: '131',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow Appeal Documents View',
    value: '140',
    order: 140,
    hostcode: null,
    key: '140',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow Appeal Documents Edit',
    value: '141',
    order: 141,
    hostcode: null,
    key: '141',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow Appeal Documents Approve',
    value: '142',
    order: 142,
    hostcode: null,
    key: '142',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow Appeal Supporting Documents Edit',
    value: '143',
    order: 143,
    hostcode: null,
    key: '143',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow Appeal Requests View',
    value: '150',
    order: 150,
    hostcode: null,
    key: '150',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow Appeal Requests Interpreter',
    value: '151',
    order: 151,
    hostcode: null,
    key: '151',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow Appeal Requests Withdrawal',
    value: '152',
    order: 152,
    hostcode: null,
    key: '152',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow Appeal Requests Reopen',
    value: '153',
    order: 153,
    hostcode: null,
    key: '153',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow Appeal Requests Other',
    value: '154',
    order: 154,
    hostcode: null,
    key: '154',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow Appeal Status History',
    value: '160',
    order: 160,
    hostcode: null,
    key: '160',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow Appeal Status Name UI Party',
    value: '161',
    order: 161,
    hostcode: null,
    key: '161',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow Appeal Status Reschedule',
    value: '162',
    order: 162,
    hostcode: null,
    key: '162',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow Appeal Status History Hide',
    value: '163',
    order: 163,
    hostcode: null,
    key: '163',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow LER Search',
    value: '200',
    order: 200,
    hostcode: null,
    key: '200',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow LER Creation',
    value: '201',
    order: 201,
    hostcode: null,
    key: '201',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow LER Reports',
    value: '202',
    order: 202,
    hostcode: null,
    key: '202',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow Statistics',
    value: '300',
    order: 300,
    hostcode: null,
    key: '300',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow Statistics 1000',
    value: '310',
    order: 310,
    hostcode: null,
    key: '310',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow Statistics 1100',
    value: '311',
    order: 311,
    hostcode: null,
    key: '311',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow Statistics 1200',
    value: '312',
    order: 312,
    hostcode: null,
    key: '312',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow Statistics 1500',
    value: '313',
    order: 313,
    hostcode: null,
    key: '313',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow Statistics 2000',
    value: '314',
    order: 314,
    hostcode: null,
    key: '314',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow Statistics 2100',
    value: '315',
    order: 315,
    hostcode: null,
    key: '315',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow Statistics 3000',
    value: '316',
    order: 316,
    hostcode: null,
    key: '316',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow Statistics 3100',
    value: '317',
    order: 317,
    hostcode: null,
    key: '317',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow Statistics 3200',
    value: '318',
    order: 318,
    hostcode: null,
    key: '318',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow Statistics 4000',
    value: '319',
    order: 319,
    hostcode: null,
    key: '319',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow Statistics 5000',
    value: '320',
    order: 320,
    hostcode: null,
    key: '320',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow Employer Search Forms View',
    value: '400',
    order: 400,
    hostcode: null,
    key: '400',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow Employer Search Forms Edit',
    value: '401',
    order: 401,
    hostcode: null,
    key: '401',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow Employer Search Forms External Comment',
    value: '402',
    order: 402,
    hostcode: null,
    key: '402',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow Employer Search Benefit Forms View',
    value: '403',
    order: 403,
    hostcode: null,
    key: '403',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow Employer Search Benefit Forms Edit',
    value: '404',
    order: 404,
    hostcode: null,
    key: '404',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow Employer Email View',
    value: '410',
    order: 410,
    hostcode: null,
    key: '410',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow Employer Email Editor (Individual)',
    value: '411',
    order: 411,
    hostcode: null,
    key: '411',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow Employer Email Editor (Group)',
    value: '412',
    order: 412,
    hostcode: null,
    key: '412',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow Employer Notice View',
    value: '420',
    order: 420,
    hostcode: null,
    key: '420',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow Employer Quarterly Wage View',
    value: '430',
    order: 430,
    hostcode: null,
    key: '430',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow Employer Quarterly Wage Enter (UCB6)',
    value: '431',
    order: 431,
    hostcode: null,
    key: '431',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow Service Company SuperCheck Validation',
    value: '440',
    order: 440,
    hostcode: null,
    key: '440',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow Service Company Quarterly Wage View',
    value: '441',
    order: 441,
    hostcode: null,
    key: '441',
    selected: false,
    hide: false,
  },
  {
    name: "Allow Service Company Edit of Employer's Quarterly Wage (B6)",
    value: '442',
    order: 442,
    hostcode: null,
    key: '442',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow Misclassifed Search View',
    value: '450',
    order: 450,
    hostcode: null,
    key: '450',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow Fraud Search View',
    value: '460',
    order: 460,
    hostcode: null,
    key: '460',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow Fraud Configure Module',
    value: '461',
    order: 461,
    hostcode: null,
    key: '461',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow Fraud View Incidences',
    value: '462',
    order: 462,
    hostcode: null,
    key: '462',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow Audit Supervisor Search View',
    value: '470',
    order: 470,
    hostcode: null,
    key: '470',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow Audit Supervisor Search Edit',
    value: '471',
    order: 471,
    hostcode: null,
    key: '471',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow Audit Field Audit Statistics Report View',
    value: '472',
    order: 472,
    hostcode: null,
    key: '472',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow Audit Core Measures Report View',
    value: '473',
    order: 473,
    hostcode: null,
    key: '473',
    selected: false,
    hide: false,
  },
  {
    name: 'Allow DMV View',
    value: '500',
    order: 500,
    hostcode: null,
    key: '500',
    selected: false,
    hide: false,
  },
];
